<!DOCTYPE html>

<html lang="fr">
	<head>
		<?php include('head_and_footer/head.php'); ?>
	</head>

	<body>
		<?php include('head_and_footer/header.php') ?>
		
		<main>
			<p class="center">Echec! Merci de remplir tous les champs</p>
			
			<form method="POST" action="add_user.php" id="createAccount">
        			<p>Créer votre compte</p>
    				<input type="text" name="last_name" id="last_name" size="30" placeholder="Nom"/>
    				<input type="text" name="first_name" id="first_name" size="30" placeholder="Prénom"/>
    				<input type="email" name="email" id="email" size="30" placeholder="Email"/>
    				<input type="text" name="login" id="login" size="30" placeholder="Login"/>
    				<input type="password" name="password" id="password" size="30" placeholder="Mot de passe"/>
        			<input type="submit" value="S'enregister" id="submit"/>
    		</form>
		</main>
		
		<?php include('head_and_footer/footer.php'); ?>
	
	</body>
</html>