<!DOCTYPE html>

<html lang="fr">
	<head>
		<?php include('head_and_footer/head.php'); ?>
	</head>

	<body>
		<?php include('head_and_footer/header.php') ?>
		<main>
			<form method="POST" action="login.php" id="createAccount">
    			<input type="text" name="login" id="login" size="30" placeholder="Login"/>
				<input type="password" name="password" id="password" size="30" placeholder="Mot de passe">
    			<div id="info">
    				<input type="submit" value="Se connecter" id="submit"/><i class="fas fa-info-circle" title="Pour accéder aux propriétés du profil admin -> login: admin; mot de passe: admin"></i>
    			</div>
    		</form>
		</main>
		<?php include('head_and_footer/footer.php'); ?>
	</body>
</html>