<?php session_start(); ?>

<!DOCTYPE html>

<html lang="fr">
	<head>
		<?php include('head_and_footer/head.php'); ?>
	</head>

	<body>
		<?php include('head_and_footer/header.php') ?>
		
		<main>
			<p class="center">Bravo! Votre compte a été enregistré. Vous pouvez maintenant utiliser toutes les fonctionnalités du site</p>
		</main>
		
		<?php include('head_and_footer/footer.php'); ?>
	
	</body>
</html>